version: "0.1"
user: sushobhitd
key: VogkmaRGCsop1RqgxN7L2iahtXwhRUMf6FcswW2SrFLOJvNN2I
testSuites: []
pre: [pwd, 'echo ${PAT}', 'echo ${qa}', echo %PAT%, echo %qa%, sed -i -e 's/MyKey/%PAT%/g' key.txt, cat key.txt, mvn compile, cat longlogs.txt]
preDirectives:
    commands: [pwd, 'echo ${PAT}', 'echo ${qa}', echo %PAT%, echo %qa%, sed -i -e 's/MyKey/%PAT%/g' key.txt, cat key.txt, mvn compile, cat longlogs.txt]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
post: [cat hyperexecute.yaml, cat longlogs.txt]
postDirectives:
    commands: [cat hyperexecute.yaml, cat longlogs.txt]
    shell: ""
    workingDirectory: ""
env:
    qa: Muralee
jobLabel:
    - HYP-2923
    - HYP-3554
    - HYP-3555
    - muralee
    - smartUI
runson: win
autosplit: true
concurrency: 1
testDiscovery:
    command: .hyperexecute/snooper  --targetOs=win --featureFilePaths=src/main/**/ --frameWork=java --query="@Addition AND @me"| sed -n 1,'5p'
    mode: static
    type: raw
testDiscoveryResult:
    - src/main/java/Features/googlesearch_1.feature:8
testRunnerCommand: mvn test `-Dcucumber.options="$test" `-Dscenario="$test" `-Dmaven.repo.local=m2_cache_dir
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
maxRetries: 2
dataJsonPath:
    - src/datame.json
    - src/data1.json
    - me/data.json
    - data.json
jobID: 42e623ed-40fd-4113-82eb-dbf978b639e2
mergeArtifacts: true
stripParentDirectory: true
taskIdentifierInNonConflictingArtefacts: true
codeDirectory: cucumber-testNG-smartui-hyperexecute-sample
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: true
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: taiko
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
collectLocalGitData: false
